"""Skill activation: diffs and side-effects.

This module contains the logic for:

- Computing which skills changed state between two snapshots
  (:func:`compute_unlock_diff`).
- Instantiating a skill (creating its SKILL.md file if absent) when activated.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from .engine import ACTIVATED, PENDING, compute_skill_states
from .state import REPO_ROOT

SKILLS_DIR = REPO_ROOT / ".claude" / "skills"


def compute_unlock_diff(
    before_state: dict[str, Any],
    after_state: dict[str, Any],
    prereqs: dict[str, Any],
) -> dict[str, list[str]]:
    """Return skills that changed status between two states.

    Output keys:
        - ``newly_activated``: were not activated before, now are
        - ``newly_pending``: were todo/dormant, now pending
        - ``still_dormant``: still dormant (unchanged but useful for UX)
    """
    before = compute_skill_states(before_state, prereqs)
    after = compute_skill_states(after_state, prereqs)
    newly_activated = []
    newly_pending = []
    still_dormant = []
    for skill_id, after_status in after.items():
        before_status = before.get(skill_id)
        if after_status == ACTIVATED and before_status != ACTIVATED:
            newly_activated.append(skill_id)
        elif after_status == PENDING and before_status not in (PENDING, ACTIVATED):
            newly_pending.append(skill_id)
        elif after_status == "dormant":
            still_dormant.append(skill_id)
    return {
        "newly_activated": sorted(newly_activated),
        "newly_pending": sorted(newly_pending),
        "still_dormant": sorted(still_dormant),
    }


def activate_skill(
    skill_id: str,
    state: dict[str, Any],
    prereqs: dict[str, Any],
    skills_dir: Path | None = None,
) -> dict[str, Any]:
    """Mark a skill as activated in ``state`` and ensure its SKILL.md exists.

    The function is idempotent: re-activating a skill is a no-op.
    Returns the (mutated) state. Caller persists.
    """
    activated = list(state.get("activated_skills") or [])
    if skill_id not in activated:
        activated.append(skill_id)
    state["activated_skills"] = activated

    target_dir = (skills_dir or SKILLS_DIR) / skill_id
    skill_file = target_dir / "SKILL.md"
    if not skill_file.exists():
        spec = (prereqs.get("skills") or {}).get(skill_id, {})
        target_dir.mkdir(parents=True, exist_ok=True)
        skill_file.write_text(_render_skill_stub(skill_id, spec), encoding="utf-8")
    return state


def _render_skill_stub(skill_id: str, spec: dict[str, Any]) -> str:
    """Render a placeholder SKILL.md for a newly activated skill.

    The real skill content is expected to be authored separately; this stub
    just makes the skill discoverable and records its prerequisites.
    """
    required = ", ".join(spec.get("required") or []) or "—"
    optional = ", ".join(spec.get("optional") or []) or "—"
    schedule = spec.get("schedule") or "—"
    category = spec.get("category") or "—"
    unlock = spec.get("unlock_message") or ""
    return (
        f"---\n"
        f"name: {skill_id}\n"
        f"description: {unlock}\n"
        f"status: activated-stub\n"
        f"version: 0.1\n"
        f"---\n\n"
        f"# /{skill_id}\n\n"
        f"_Stub generated by OpowAI setup engine. Replace with the full spec._\n\n"
        f"- **Category:** {category}\n"
        f"- **Required:** {required}\n"
        f"- **Optional:** {optional}\n"
        f"- **Schedule:** {schedule}\n"
    )
